### ISSUE TITLE
Validacija neispravnog JMBG

### ISSUE THREAD

**Issue by ce10003** [draganjovanovic1/JSTools#2]
JMBG: 2812961710040

Prolazi validaciju kao ispravan a http://jmbg.brmbrm.com/ kaže da je neispravan... 

Pozdrav, Ce10003

**Comment by draganjovanovic1** [comment]
Matični broj je ispravan. Ako pokušate sve cifre na brmbrm kao kontrolne za 281296171004 videli biste da ni jedna ne prolazi što bi značilo da 4. rođeno muško dete toga dana u Beogradu ne dobija JMBG.

Kontroli broj se računa po modulu 11 i može biti jednocifren ili dvocifren:  
- ako je kontrolna cifra između 1 i 9, ostaje ista
- ako je kontrolna cifra veća od 9, postaje nula

Evo kontrole koja prolazi za prijavljeni JMBG:
http://www.eclectica.ca/howto/modulus-11-self-check.php?start=281296171004&count=&generate=Generate#calculator

Pozdrav,
Dragan

**Comment by ce10003** [comment]
Svaka čast na preciznom i brzom odgovoru. Izgleda da u PHP kodu koji koristim nedostaje provera kontrolne cifre da li prelazi vrednost 9. U primeru koji sam podneo ona bi trebala biti 11 što znači da se vraća na nulu. 

Hvala i pozdrav, Ce10003
